name: remix_mvp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  dotted_border: ^2.1.0
  fluentui_system_icons: ^1.1.265
  desktop_drop: ^0.5.0
  just_audio: ^0.9.34
  path_provider: ^2.1.1
  just_audio_web: ^0.4.8
  flutter_audio_waveforms: ^1.2.1+8 
  video_thumbnail: ^0.5.3
  chewie: ^1.8.5
  video_player: ^2.9.2
  video_player_web: ^2.3.3
  ffmpeg_wasm: ^1.0.3
  video_trimmer:
    git:
      url: https://github.com/bluejoyq/video_trimmer.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
  - family: NotoSansKR
    fonts:
    - asset: assets/fonts/NotoSansKR-Light.ttf
      weight: 300
    - asset: assets/fonts/NotoSansKR-Regular.ttf
      weight: 400
    - asset: assets/fonts/NotoSansKR-Medium.ttf
      weight: 500
    - asset: assets/fonts/NotoSansKR-Bold.ttf
      weight: 700