name: Build and deploy flutter web app

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter build web --base-href "/${{ github.event.repository.name }}/"
